spring:
  application:
    name: gateway
cloud:
  gateway:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
      routes:
        - id: service-users
          uri: http://localhost:8081/api
          predicates:
            - Path=/users/**
        - id: service-offers
          uri: http://localhost:8082/api
          predicates:
            - Path=/offers/**
        - id: service-orders
          uri: http://localhost:8083/api
          predicates:
            - Path=/orders/**
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
